global using Xunit;
global using Xunit.Abstractions;
global using Moq;
global using FluentValidation;
global using Microsoft.AspNetCore.Mvc;
global using Newtonsoft.Json;
global using ProjectPlanner.Business.Validation;
global using Project_Planner.Controllers;
global using ProjectPlanner.Application.Services;
